#!/bin/bash
# Ottimizzazione
echo 'Ciao!'
echo 'This script allow international Deepin users to modify the Source.List and get the full advantages (download speed) from using a local Mirror (nearest mirror)'
echo 'When you run it, a backup of original Source.list will be placed in the same directory of the script'
echo ''
PS3='Select yout Country, the best default Mirror will be configurated: '
options=("Italy" "Austria" "Belgium" "Japan" "Latvia" "Philippines" "Poland" "Turkey" "Brazil" "Bulgaria" "Canada" "Germany" "Greece" "Indonesia" "Ireland" "Russia" "Singapore" "Slovakia" "South Africa" "Sweden" "United States of America" "United Kingdom" "Vietnam" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Italy")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://ba.mirror.garr.it/mirrors/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Austria")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://mirror.inode.at/data/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Belgium")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://ftp.belnet.be/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Japan")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://www.ftp.ne.jp/Linux/packages/deepin/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Latvia")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://deepin.koyanet.lv/packages/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Philippines")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://mirrors.dotsrc.org/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Poland")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://piotrkosoft.net/pub/mirrors/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Turkey")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://mirror.veriteknik.net.tr/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Brazil")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://sft.if.usp.br/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Bulgaria")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://deepin.ipacct.com/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Canada")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://deepin.mirror.globo.tech/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Germany")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://ftp.fau.de/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Greece")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://ftp.cc.uoc.gr/mirrors/linux/deepin/packages/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Indonesia")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://kartolo.sby.datautama.net.id/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Ireland")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://ftp.heanet.ie/pub/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Russia")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://mirror.yandex.ru/mirrors/deepin/packages/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Singapore")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://mirror.0x.sg/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Slovakia")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://tux.rainside.sk/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;

        "South Africa")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://www.ftp.saix.net/linux/distributions/linux-deepin/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;		
        "Sweden")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://ftp.acc.umu.se/mirror/linuxdeepin/packages/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;	
        "United States of America")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://mirror.jmu.edu/pub/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;	
        "United Kingdom")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://www.mirrorservice.org/sites/packages.linuxdeepin.com/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
        "Vietnam")
		echo ''
		echo 'Ok, now I will force Deepin to use your local Mirror'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://mirror.freedif.org/Deepin/deepin/ panda main contrib non-free
EOF'
		sudo apt update
		echo ''
		;;
		"Quit")
	    echo 'Thanks to use this script, continue to support Deepin Project..Worth the Diggin!'
		break
		;;
        *) echo invalid option;;
    esac
done