#!/bin/bash
# This file is part of the https://gist.github.com/Maxximo88
# Copyright (c) 2017 Carofano Massimo Antonio
# 
# This program is free software: you can redistribute it and/or modify  
# it under the terms of the GNU General Public License as published by  
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but 
# WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License 
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
echo 'Ciao, questo script nasce a supporto della Community Italiana di Deepin, per facilitare il processo post installazione.'
echo 'Tra i software consiglio Gimp (alternativa ad Adobe Photoshop), Natron (alternativa ad Adobe After Effect), Lightworks (alternativa ad Adobe Premiere), RawTherapee (alternativa ad Adobe Lightroom), Blue Fish (alternativa ad Adobe Dreamweaver), Inkscape (alternativa a Corel Draw), Blender (alternativa a 3DsMax), OpenSCAD (alternativa ad Autodesk AutoCAD)'
echo ''
echo 'Per prima cosa, ricordati di impostare il Mirror italiano GARR, forzando Deepin ad utilizzarlo ed accelerando vistosamente la velocità di download.'
echo ''
PS3='Seleziona il numero corrispondende comando che desideri avviare: '
options=("Imposta il mirror Italiano GARR" "Installa tutti i software consigliati" "Ampliamento funzionalità terminale" "Fonts aggiuntivi" "Flash Player" "Multimedia" "Libre Office" "Gimp" "Natron" "Lightworks" "RawTherapee" "Blue Fish" "Inkscape" "Blender" "OpenSCAD" "gDebi" "Synaptic" "Evince" "Bleachbit" "Open JDK8" "VLC Media Player" "Gestore pacchetti Snap" "iFuse per supporto Apple iPhone/iPad/iPod" "Neofetch" "Fonts Google Roboto" "Pulizia Distro" "Termina")
select opt in "${options[@]}"
do
    case $opt in
        "Imposta il mirror Italiano GARR")
		echo ''
		echo 'Ora modificherò il tuo Source.List forzando Deepin ad utilizzare il Mirror Italiano GARR, ovviamente una copia del file Source.list verrà depositata nella medesima cartella in cui è presente questo script'
		echo ''
cd $HOME &
sudo cp /etc/apt/sources.list backup.sources.list
sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
# deb-src http://packages.deepin.com/deepin unstable main contrib non-free
##########################################################################################
deb [by-hash=force] http://ba.mirror.garr.it/mirrors/deepin/ panda main contrib non-free
EOF'
			sudo apt update
			echo ''
			echo 'Beh, ora che hai agganciato Deepin al Mirror italiano possiamo proseguire!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
		"Installa tutti i software consigliati")
            sudo apt-get install -y software-properties-common dirmngr ttf-mscorefonts-installer flashplugin-nonfree libdvd-pkg libdvdread4 python3 libreoffice-base libreoffice-style-sifr gimp natron lightworks rawtherapee bluefish inkscape blender openscad gdebi synaptic evince ifuse bleachbit openjdk-8-jre icedtea-8-plugin vlc snapd
            sudo dpkg-reconfigure libdvd-pkg
		    	sudo apt-get install -f
			sudo apt-get --purge autoremove
			sudo apt-get autoclean
			sudo apt-get clean
			sudo apt-get -y install deborphan
			sudo apt-get --purge remove `deborphan`
			sudo apt-get --purge remove `deborphan --libdev`
		    sudo apt-get install curl libcurl3 php5-curl
			echo "deb http://dl.bintray.com/dawidd6/neofetch jessie main" | sudo tee -a /etc/apt/sources.list
			curl -L "https://bintray.com/user/downloadSubjectPublicKey?username=bintray" -o Release-neofetch.key && sudo apt-key add Release-neofetch.key && rm Release-neofetch.key
			sudo apt-get update
			sudo apt-get install neofetch
			neofetch
	        	mkdir -p $HOME/roboto-src cd $HOME/roboto-src
			git clone https://github.com/google/roboto.git
			pip install --user virtualenv virtualenv roboto-env source roboto-env/bin/activate
			cd roboto pip install -r requirements.txt
			cd roboto make
			echo ''
			echo 'Beh, carino Neofetch eh? Ad ogni modo, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
        "Ampliamento funzionalità terminale")
            sudo apt-get install -y software-properties-common && sudo apt-get install dirmngr
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Fonts aggiuntivi")
	    sudo apt-get install -y ttf-mscorefonts-installer
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Flash Player")
	    sudo apt-get install -y flashplugin-nonfree
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Multimedia")
	    sudo apt-get install -y libdvd-pkg libdvdread4 python3 && sudo dpkg-reconfigure libdvd-pkg
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Libre Office")
	    sudo apt-get install -y libreoffice-base && sudo apt-get install libreoffice-style-sifr
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Gimp")
	    sudo apt-get install -y gimp
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Natron")
	    sudo apt-get install -y natron
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Lightworks")
	    sudo apt-get install -y lightworks
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"RawTherapee")
	    sudo apt-get install -y rawtherapee
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Blue Fish")
	    sudo apt-get install -y bluefish
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Inkscape")
	    sudo apt-get install -y inkscape
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Blender")
	    sudo apt-get install -y blender
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"OpenSCAD")
	    sudo apt-get install -y openscad
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"gDebi")
	    sudo apt-get install -y gdebi
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Synaptic")
	    sudo apt-get install -y synaptic
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Evince")
	    sudo apt-get install -y evince
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Bleachbit")
		sudo apt-get install bleachbit -y
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Open JDK8")
		sudo apt-get install openjdk-8-jre icedtea-8-plugin -y
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	 "VLC Media Player")
	 	sudo apt-get install vlc -y
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Gestore pacchetti Snap")
	        sudo apt-get install -y snapd
	        sudo snap install hello
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"iFuse per supporto Apple iPhone/iPad/iPod")
	        sudo apt-get install -y ifuse
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Neofetch")
	        sudo apt-get install curl libcurl3 php5-curl
			echo "deb http://dl.bintray.com/dawidd6/neofetch jessie main" | sudo tee -a /etc/apt/sources.list
			curl -L "https://bintray.com/user/downloadSubjectPublicKey?username=bintray" -o Release-neofetch.key && sudo apt-key add Release-neofetch.key && rm Release-neofetch.key
			sudo apt-get update
			sudo apt-get install neofetch
			neofetch
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Fonts Google Roboto")
	        mkdir -p $HOME/roboto-src cd $HOME/roboto-src
		git clone https://github.com/google/roboto.git
		pip install --user virtualenv virtualenv roboto-env source roboto-env/bin/activate
		cd roboto pip install -r requirements.txt
		cd roboto make
			echo ''
			echo 'Beh, proseguiamo!'
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;;
	"Pulizia Distro")
			echo ''
			echo 'Inizio col verificare i pacchetti difettosi'
			echo ''
			sudo apt-get install -f
			echo ''
			echo 'Proseguo eliminando le dipendenze inutili'
			echo ''
			sudo apt-get --purge autoremove
			echo ''
			echo 'Verifico ed elimino i pacchetti obsoleti'
			echo ''
			sudo apt-get autoclean
			echo ''
			echo 'Rimuovo i pacchetti scaricati oramai inutili'
			echo ''
			sudo apt-get clean
			echo ''
			echo 'Verifico la presenza di Deborphan, nel caso installandolo, per eliminare le librerie orfane'
			echo ''
			sudo apt-get -y install deborphan
			sudo apt-get --purge remove `deborphan`
			echo ''
			echo 'Elimino ora le librerie orfane relative allo sviluppo)'
			echo ''
			sudo apt-get --purge remove `deborphan --libdev`
			echo ''
			echo 'Ti ricordo le opzioni: 1.Imposta il mirror Italiano GARR; 2.Installa tutti i software consigliati; 3.Ampliamento funzionalità terminale; 4.Fonts aggiuntivi; 5.Flash Player; 6.Multimedia; 7.Libre Office; 8.Gimp; 9.Natron; 10.Lightworks; 11.RawTherapee; 12.Blue Fish; 13.Inkscape; 14.Blender; 15.OpenSCAD; 16.gDebi; 17.Synaptic; 18.Evince; 19.Bleachbit; 20.Open JDK8; 21.VLC Media Player; 22.Gestore pacchetti Snap; 23.iFuse per supporto Apple iPhone/iPad/iPod; 24.Neofetch; 25.Fonts Google Roboto; 26.Pulizia Distro; 27.Termina'
	    ;; 
	"Termina")
	    	echo 'Beh, spero che questo script sia apprezzato...Alla prossima!'
		break
		;;
        *) echo invalid option;;
    esac
done
